### ISSUE TITLE
Pair rate calculation not updated after changing date

### ISSUE THREAD

**Issue by stanley90** [spk/money-open-exchange-rates#63] opened 2020-06-26 12:19 UTC
After loading rates for a particular date, setting a different date and updating rates, the USD-based rates change, but calculated pairs do not:

```
bank = Money::Bank::OpenExchangeRatesBank.new
bank.app_id = ...

puts 'CURRENT'
bank.date = nil
bank.update_rates
usd_chf = bank.get_rate('USD', 'CHF')
usd_eur = bank.get_rate('USD', 'EUR')
eur_chf = bank.get_rate('EUR', 'CHF')
puts [usd_chf, usd_eur, eur_chf, 1 / usd_eur * usd_chf]

puts 'HISTORICAL'
bank.date = 1.month.ago.to_date
bank.refresh_rates
usd_chf = bank.get_rate('USD', 'CHF')
usd_eur = bank.get_rate('USD', 'EUR')
eur_chf = bank.get_rate('EUR', 'CHF')
puts [usd_chf, usd_eur, eur_chf, 1 / usd_eur * usd_chf]
```

output:
```
CURRENT
0.948306 # USD/CHF
0.89205 # USD/EUR
1.06306373 # EUR/CHF
1.0630637296115688 # cross check
HISTORICAL
0.965503 # USD/CHF
0.910865 # USD/EUR
1.06306373 # EUR/CHF - not updated - WRONG
1.0599847397803186 # cross check
```

Is this a bug? Am I doing something wrong? Should I not reuse the bank for different dates and rather instantiate a new one?

**Comment by spk** [comment] 2020-07-05 11:21
Thanks for the detailed bug report I will try to reproduce and check this

**Comment by spk** [comment] 2020-07-06 10:23
> puts 'HISTORICAL'
> bank.date = 1.month.ago.to_date
> bank.refresh_rates
> usd_chf = bank.get_rate('USD', 'CHF')
> usd_eur = bank.get_rate('USD', 'EUR')
> eur_chf = bank.get_rate('EUR', 'CHF')
> puts [usd_chf, usd_eur, eur_chf, 1 / usd_eur * usd_chf]
> ```
> Is this a bug? Am I doing something wrong? Should I not reuse the bank for different dates and rather instantiate a new one?

In the historical block you are using `refresh_rates` this will just fetch the rates on API but will not update rates on memory so it will keep the firsts ones (CURRENT).
If its a one shot thing maybe try to have a dedicated bank instance for your historical then `update_rates` and see if its working for you ?

**Comment by anton-smagin** [comment] 2020-09-02 11:59
@spk hey i created a PR on this issue, because we faced same problem cross courses not updated after update_rates which leads to not correct calculation in our app. what do you think?

https://github.com/spk/money-open-exchange-rates/pull/64

**Comment by spk** [comment] 2020-09-07 09:55
hey @anton-smagin thanks for working on this, I see now what is the issue going to merge this and release soon™️

**Comment by spk** [comment] 2020-09-11 14:30
Fixes released in https://github.com/spk/money-open-exchange-rates/releases/tag/v1.4.0

**Comment by spk** [comment] 2020-09-11 14:30
Fixes released in https://github.com/spk/money-open-exchange-rates/releases/tag/v1.4.0

**Comment by spk** [comment] 2020-09-11 14:30
Fixes released in https://github.com/spk/money-open-exchange-rates/releases/tag/v1.4.0

**Comment by spk** [comment] 2020-09-11 14:30
Fixes released in https://github.com/spk/money-open-exchange-rates/releases/tag/v1.4.0

**Comment by spk** [comment] 2020-09-11 14:30
Fixes released in https://github.com/spk/money-open-exchange-rates/releases/tag/v1.4.0

**Closed** 2020-11-05 20:08 UTC
